### PR TITLE
Add Open API 3 spec

### PR DESCRIPTION
**Pull request by Stranger6667**
As briefly discussed in #2 I added an Open API 3 schema for the API :) 

At https://editor.swagger.io/, it renders like this and provides a web-UI :) Let me know if you'd like me to change some definitions, etc.

Screenshot from 2020-12-05 15-54-12

### CODE REVIEW

**Comment by redraw** [comment]
Great! I've noticed that frameworks like FastAPI automatically generates them based on the methods params and typing hints. It might have been an alternative when I started. Did you handwrite this?
You can just add a flask view to serve the schema, and it's ready to merge :+1:

**Comment by Stranger6667** [comment]
> Did you handwrite this?

Yes, with a little help of [JSON Schema inference tools](https://jsonschema.net/home). 

> I've noticed that frameworks like FastAPI automatically generates them based on the methods params and typing hints. It might have been an alternative when I started

From my side, I'd like to say that FastAPI is a great tool :) However, it might [generate invalid schemas](https://github.com/tiangolo/fastapi/issues/240) due to the usage of JSON Schema Draft 7 (instead of so-called Draft 5) via `pydantic` and without Open API specific modifications. But in the overwhelming number of cases, everything works great :)

> You can just add a flask view to serve the schema, and it's ready to merge +1

I will do that! What do you think about having the swagger-UI there as well?

**Comment by Stranger6667** [comment]
I added `swagger-UI` on `/docs,` and everything renders as on the screenshot above :) Except for a small nuance due to the local deployment - there is a small block with "INVALID" text at the bottom of the page. Still, it happens because the UI using an [external validator](https://validator.swagger.io/) that tries to access the spec, which is not accessible in this case since it is a local address.

Since the initial commit, I added also the local server to the servers list - `http://0.0.0.0:8000/`. In the perfect case, it would be nice to render the spec with the actual deployed address, but I think it is a good enough way to add the local server to the Swagger UI when working locally :)

**Comment by redraw** [comment]
> Since the initial commit, I added also the local server to the servers list - http://0.0.0.0:8000/. In the perfect case, it would be nice to render the spec with the actual deployed address, but I think it is a good enough way to add the local server to the Swagger UI when working locally :)

Yeah, that's enough for now, thanks for the work! 
I'll try schematesis ;)

**Comment by Stranger6667** [comment]
You are very welcome! :)

**Pull request merged**
